---
name: Sample123
description: "Rule which sends an email when an email from johndoe@gmail.com is received"
pack: semail
enabled: true
trigger:
  type: semail.imap.message
  parameters: {}
criteria:
  trigger.subject:
    pattern: vm create
    type: contains
action:
  ref: core.local
  input:
      cmd: "HI"
